### ISSUE TITLE
One-class classification error

### ISSUE THREAD

**Issue by Didimo8** [eminSerin/NBS-Predict#30]
hello to everyone, unfortunately I encounter an error that I can't explain by simply comparing two groups.
I can only see the accuracy while for all the other parameters NBSPredict gives an error: "Warning: Only one class present! sensitivity does support one-class classification, and being set to NaN Please use Accuracy instead!"
thanks for any replies

**Comment by eminSerin** [comment]
Hi,

Thank you for your interest in our toolbox and opening an issue regarding your problem.

Regarding the error you mentioned, it is possible to encounter it if there is only one class in a given CV fold. This can happen due to a low sample size or, more importantly, an unequal number of subjects in each group. 

Please give me more details about your sample size to understand your situation better and provide accurate assistance. I would be happy to help you resolve this issue.
